server:
  port: ${PORT:5000}

base-url: /api
rollbar_token: ${ROLLBAR_TOKEN:6878a44065084d5cae10f1872d45bac0}

jwt:
  secret: ${JWT_SECRET:secret}

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hidden-method:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate


springdoc:
  api-docs:
    path: /swagger.html